import '../models/movie_model.dart';
import 'dart:math';

class MovieService {
  final List<Map<String, String>> movies = [

  {"title": "DRISHYAM", "clue": "A cable TV operator uses his knowledge of cinema to cover up a crime and protect his family from police suspicion after an accidental murder."},
  {"title": "MANICHITRATHAZHU", "clue": "When a newlywed woman is haunted by a tragic dancer's spirit, a psychiatrist must uncover the truth behind her frightening transformation."},
  {"title": "PREMAM", "clue": "Follows George through three stages of love — from a shy teen to a bearded college guy to a responsible man — as he searches for true love."},
  {"title": "ROMANCHAM", "clue": "A group of jobless young men in Bengaluru mess with a Ouija board, leading to eerie and hilarious consequences that shake up their lives."},
  {"title": "JAYA JAYA JAYA JAYA HE", "clue": "A quiet girl in an arranged marriage transforms herself and begins to fight back after years of abuse and being underestimated."},
  {"title": "KUMBALANGI NIGHTS", "clue": "In a scenic village, four brothers with troubled pasts struggle to live together, until love, responsibility, and a psychotic 'perfect' man change their lives."},
  {"title": "PAZHASSI RAJA", "clue": "Based on the life of Kerala Varma Pazhassi Raja, who led guerrilla battles against British rule long before the 1857 rebellion."},
  {"title": "CHARLIE", "clue": "A mysterious artist leaves behind clues and artworks that lead a young woman on an emotional journey to find and understand him."},
  {"title": "NNA THAN CASE KODU", "clue": "A reformed thief files a legal case against corrupt officials, turning his accidental misfortune into a bold fight for justice."},
  {"title": "LUCIFER", "clue": "Following the death of a charismatic leader, Kerala's political stage turns into a battlefield, where a mysterious figure from the past returns to restore order."},
  {"title": "THONDIMUTHALUM DRIKSAKSHIYUM", "clue": "A chain-snatching incident leads to an unexpected bond between a newlywed couple and a thief during their long stay at a rural police station."},
  {"title": "BANGALORE DAYS", "clue": "Three close cousins move to Bangalore, each facing personal transformations through love, heartbreak, and adventure in the bustling city."},
  {"title": "MAYANADHI", "clue": "A small-time criminal on the run tries to reconnect with his ex-girlfriend, but fate and his past decisions slowly catch up to him."},
  {"title": "EE. MA. YAU.", "clue": "A son tries to fulfill his father's wish for a grand funeral, but a series of absurd and tragic events turn the funeral into chaos."},
  {"title": "MAHESHINTE PRATHIKAARAM", "clue": "A simple photographer vows not to wear his slippers again until he avenges the humiliation he faced in front of the town."},
  {"title": "ANJAAM PATHIRAA", "clue": "A consulting psychologist helps the police hunt down a mysterious serial killer who targets cops and leaves behind chilling clues."},
  {"title": "USTHAD HOTEL", "clue": "A young man trained in five-star cooking finds his purpose working with his grandfather in a beachside hotel serving simple biriyani."},
  {"title": "SUDANI FROM NIGERIA", "clue": "After an African footballer gets injured, his unexpected bond with the team manager and the local community forms a heartwarming tale."},
  {"title": "THE GREAT INDIAN KITCHEN", "clue": "A newly married woman slowly realizes the oppressive traditions and routines expected from a wife, and silently rebels against them."
  },
  {"title": "TRAFFIC", "clue": "A donor heart must be delivered across the city during peak traffic, bringing together strangers in a life-saving real-time mission."},
  {"title": "1983", "clue": "A young man obsessed with cricket sacrifices his dreams for family responsibilities, only to pass on his love for the game to his son."},
  {"title": "JOJI", "clue": "Loosely based on Macbeth, a weak son in a wealthy family conspires to seize power when his dominating father falls ill."},
  {"title": "HRIDAYAM", "clue": "Chronicles the emotional highs and lows of a man from his college life through heartbreak, self-discovery, and maturity."},
  {"title": "ANDROID KUNJAPPAN", "clue": "An old man reluctant to accept modern technology grows emotionally attached to a humanoid robot that replaces his absent son."},
  {"title": "NAYATTU", "clue": "Three police officers flee the system after being framed for a politically sensitive case just before state elections."},
  {"title": "C U SOON", "clue": "A techie investigates the disappearance of his girlfriend using digital clues, revealing a deeper human trafficking plot."},
  {"title": "ACTION HERO BIJU", "clue": "A day-in-the-life tale of a sincere sub-inspector juggling cases, public service, and his personal life."},
  {"title": "KANNUR SQUAD", "clue": "A covert police team chases dangerous criminals across states using guts, ground intelligence, and teamwork."},
  {"title": "MALIK", "clue": "Spanning several decades, this story follows a man’s rise from local youth to revered leader amid religious and political turmoil."},
  {"title": "THALLUMAALA", "clue": "A fun-loving guy’s life spirals into chaos when viral fights and a wedding brawl make him an overnight sensation."},
  {"title": "ISHQ", "clue": "A couple’s romantic night out is interrupted by strangers, leading to a dark exploration of male ego and moral policing."},
  {"title": "VARANE AVASHYAMUNDU", "clue": "A single mother, her daughter, and a quiet army man explore relationships, matchmaking, and self-discovery in Chennai."},
  {"title": "RORSCHACH", "clue": "A grieving man moves into a remote house, hiding a sinister motive while confronting people connected to his wife's death."},
  {"title": "PRANCHIYETTAN & THE SAINT", "clue": "A wealthy rice merchant consults Saint Francis in his imagination while trying to earn social respect and love."},
  {"title": "AMEN", "clue": "A saxophone player in a church band falls in love with a rich girl, amidst divine interventions and small-town politics."},
  {"title": "KAPPA", "clue": "Turf wars and hidden pasts unravel as Kochi’s underworld gangs clash with politics and police."},
  {"title": "SALT N' PEPPER", "clue": "A misdial leads two food lovers to fall in love over recipes, bringing warmth and nostalgia through their culinary memories."},
  {"title": "ORE KADAL", "clue": "An intellectual economist’s affair with a married woman leads to emotional destruction and realizations about love."},
  {"title": "THIRA", "clue": "A human rights activist joins forces with a doctor to rescue girls from a human trafficking ring."},
  {"title": "CHURULI", "clue": "Two undercover cops enter a remote, mysterious village where people speak in riddles and time feels broken."},
  {"title": "NEELAKASHAM PACHAKADAL CHUVANNA BHOOMI", "clue": "Two friends go on a soul-searching motorbike journey across India, facing culture, politics, and self-realization."},
  {"title": "VELLIMOONGA", "clue": "A middle-aged man balances rural politics with his quest for love, bringing comedy and charm."},
  {"title": "THIRAKKATHA", "clue": "A filmmaker searches for a forgotten actress's untold story, exploring love, fame, and loss."},
  {"title": "KIREEDAM", "clue": "A young man’s dream of becoming a police officer crumbles after a street fight forces him into a path of violence."},
  {"title": "KOODE", "clue": "After his sister's death, a withdrawn man begins to rediscover joy through her lingering presence and memories."},
  {"title": "NJAN", "clue": "A writer investigates the forgotten life of a mysterious revolutionary who disappeared decades ago."},
  {"title": "BHOOTHAKANNADI", "clue": "A lonely watchmaker believes he saw a child abuse case through a mirror, leading to his mental breakdown and social alienation."},
  {"title": "CHITHRAM", "clue": "A man is hired to pretend as a husband to impress a dying father, but things take an emotional turn."},
  {"title": "THENMAVIN KOMBATH", "clue": "Two men fight for the love of a woman while traveling through scenic Kerala villages."},
  {"title": "KIREEDAM", "clue": "A young man’s dream of becoming a police officer is shattered when fate forces him into violence."},
  {"title": "SADANANDANTE SAMAYAM", "clue": "A priest’s peaceful life turns upside down when his family lands into legal and marital troubles."},
  {"title": "KILUKKAM", "clue": "A tourist guide's life changes when a strange and rich girl appears and turns everything upside down."},
  {"title": "MEESA MADHAVAN", "clue": "A lovable thief navigates love, revenge, and redemption in a village filled with quirky characters."},
  {"title": "CID MOOSA", "clue": "A wannabe detective ends up solving a major political conspiracy using comical tricks."},
  {"title": "NADODIKATTU", "clue": "Two jobless men go to Chennai for work but accidentally land in a smuggling racket."},
  {"title": "POTHAN VAVA", "clue": "A lawyer takes on corrupt systems while dealing with a turbulent mother-son relationship."},
  {"title": "MALAYALAM", "clue": "A soldier returns to his homeland, only to face personal and political conflicts from the past."},
  {"title": "VADAKKUNOKKIYANTRAM", "clue": "A man suffers from extreme inferiority complex and jealousy over his wife's beauty."},
  {"title": "RAMJI RAO SPEAKING", "clue": "Three jobless men get involved in a kidnapping gone wrong, leading to comedy and chaos."},
  {"title": "IN HARIHAR NAGAR", "clue": "Four friends try to impress a girl, getting tangled in a crime mystery from her past."},
  {"title": "GODFATHER", "clue": "A classic feud between two powerful families becomes complicated with a love affair."},
  {"title": "LELAM", "clue": "The son of a liquor baron takes over his father’s business and confronts rivals in style."},
  {"title": "SPADIKAM", "clue": "A rebellious young man with a troubled past returns home to face his stern father."},
  {"title": "NARAN", "clue": "A fearless village strongman protects his people from external and internal threats."},
  {"title": "DEVAASURAM", "clue": "An arrogant feudal lord changes his life after a dancer humiliates him publicly."},
  {"title": "THOOVANATHUMBIKAL", "clue": "A man caught between two loves – a pure-hearted girl and a seductive escort."},
  {"title": "AKASHADOOTHU", "clue": "A terminally ill mother struggles to find homes for her children before she dies."},
  {"title": "BHARATHAM", "clue": "A classical singer is torn between family duty and guilt after his brother disappears."},
  {"title": "MAYAMOHINI", "clue": "Three men are fooled by a woman, who later turns out to be a man in disguise."},
  {"title": "SENIOR MANDRAKE", "clue": "A cursed statue brings havoc into the lives of everyone who tries to own it."},
  {"title": "CHAANDUPOTTU", "clue": "A man raised like a girl grows up facing identity and societal challenges."},
  {"title": "KATHAVASIS", "clue": "A priest returns to his old village and uncovers the exploitation of the poor."},
  {"title": "VASANTHAMALLIKA", "clue": "A family with secrets lives under one roof, hiding truths that come out one by one."},
  {"title": "HIS HIGHNESS ABDULLAH", "clue": "A hired assassin disguises as a classical singer to enter a royal family."},
  {"title": "PARINAYAM", "clue": "A Namboothiri widow's resistance against societal norms becomes a statement for change."},
  {"title": "PERUMAZHAKKALAM", "clue": "Two women, connected by tragedy, meet to save one man’s life from execution."},
  {"title": "BHOOTHAM", "clue": "A small boy befriends a ghost who helps him fight against evil forces."},
  {"title": "VELLANAKALUDE NAADU", "clue": "A sincere PWD officer fights corruption while constructing roads in a rural town."},
  {"title": "MUKUNDAN UNNI ASSOCIATES", "clue": "A clever young lawyer stops at nothing to climb the legal ladder of success."},
  {"title": "LEFT RIGHT LEFT", "clue": "Three lives connected by politics, violence, and past trauma intersect dramatically."},
  {"title": "PUNYALAN AGARBATHIS", "clue": "An entrepreneur tries to make incense sticks from elephant dung amidst bureaucratic hurdles."},
  {"title": "KALI", "clue": "A young man with anger issues finds himself and his wife in a tense situation at a roadside eatery."},
  {"title": "KAMMARA SAMBHAVAM", "clue": "The story of a freedom fighter is retold with twists, showing how history is manipulated."},
  {"title": "ODIYAN", "clue": "A man from a mythical clan of shape-shifters returns home after years of exile."},
  {"title": "KAALAPANI", "clue": "A freedom fighter is wrongfully imprisoned in the Andaman jail during the British era."},
  {"title": "RAJAMANIKYAM", "clue": "A Tamil-speaking businessman solves the family feud and business crisis of his step-siblings."},
  {"title": "CHRONICLES OF NARANATH", "clue": "A legendary madman who pushed boulders uphill as part of divine satire."},
  {"title": "ENNADU KANNAANU", "clue": "A man returns from the Gulf and challenges a corrupt political system."},
  {"title": "RASATANTRA", "clue": "A man with a mysterious gift predicts disasters and tries to stop them."},
  {"title": "KATTUKUTHIRA", "clue": "A mentally unstable man is obsessed with power and fear in a decaying feudal society."},
  {"title": "YODHA", "clue": "A carefree youth gets involved in saving a young Tibetan monk from assassins."},
  {"title": "MIZHI RANDILUM", "clue": "A girl's mysterious death shakes her lover’s world and forces him to face his past."},
  {"title": "RAVANA PRABHU", "clue": "The son of a feudal lord continues his father's unfinished war with rivals."},
  {"title": "OLAPEEPI", "clue": "An old man’s memories of childhood and loneliness are revisited through a young boy’s eyes."},
  {"title": "JALAKANYAKA", "clue": "A water spirit guides a man through his grief and trauma."},
  {"title": "AAVESHAM","clue": "Three engineering students in Bengaluru get caught in gang fights and befriend a violent but charming local gangster named Ranga."},
  {"title": "AAGATHAN","clue": "A mysterious man enters a retired Army general's life, only to reveal dark truths connected to a traumatic past event."},
  {"title": "JANA GANA MANA","clue": "A professor’s murder sparks nationwide protests, but a courtroom drama reveals shocking twists about justice and manipulation."},
  {"title": "SAUDI VELLAAKKA","clue": "A small family dispute escalates into a court case, showing how the Indian legal system deeply affects ordinary lives."},
  {"title": "THANKAM","clue": "Two men from the gold business embark on a trip that unravels betrayal, mental trauma, and emotional downfall."},
];


  Future<Movie> fetchRandomMalayalamMovie() async {
    final random = Random();
    final selected = movies[random.nextInt(movies.length)];
    return Movie(title: selected['title']!, clue: selected['clue']!);
  }
}
